language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- ruby-head

before_install:
- sudo apt-get install seqan-dev
- gem install rice

install:
- ruby ext/bioseqalign/extconf.rb && cd ext/bioseqalign/ && make
